function createInitialShips(shipCapacityById) {
  return [
    {
      id: "hauler-1",
      at: "anchor_station",
      status: "idle",
      cargoCapacity: shipCapacityById["hauler-1"],
      busyUntil: 0,
      departAt: 0,
      lastKnownAt: "anchor_station",
      lastContactTick: 0,
      acquiredAtTick: 0,
    },
    {
      id: "hauler-2",
      at: "refinery",
      status: "idle",
      cargoCapacity: shipCapacityById["hauler-2"],
      busyUntil: 0,
      departAt: 0,
      lastKnownAt: "refinery",
      lastContactTick: 0,
      acquiredAtTick: 0,
    },
    {
      id: "courier-1",
      at: "indigo_station",
      status: "idle",
      cargoCapacity: shipCapacityById["courier-1"],
      busyUntil: 0,
      departAt: 0,
      lastKnownAt: "indigo_station",
      lastContactTick: 0,
      acquiredAtTick: 0,
    },
  ];
}

export function createInitialGameState({ shipCapacityById, defaultLoreSummary, now = Date.now } = {}) {
  const capacities = shipCapacityById || {};
  return {
    tick: 0,
    running: true,
    cash: 2200,
    rep: 58,
    risk: 22,
    escort: false,
    contracts: [],
    contractBoardTargetOpen: null,
    completedContracts: 0,
    tutorialDone: false,
    currentScenario: 1,
    scenario2Activated: false,
    scenario3Activated: false,
    scenario4Activated: false,
    ships: createInitialShips(capacities),
    delayedMessages: [],
    nextContract: 1,
    selection: {
      selectedShipId: null,
      pending: null,
      allowedDestinationIds: [],
      dockableShipIds: [],
    },
    loreSummary: defaultLoreSummary || "",
    dialogueDb: {},
    ambientNeutralConversation: [],
    ambientDialoguePools: {},
    characterNameRegistry: null,
    latencyBriefed: false,
    lastAmbientLine: null,
    lastAmbientChatterTick: -Infinity,
    mapData: null,
    shipRegistry: null,
    conflictOutcomes: null,
    buddeData: null,
    civilianNpcs: [],
    scenarioDialogue: {},
    scenario2Dialogue: null,
    scenario3Dialogue: null,
    scenario4Dialogue: null,
    playerRequestDialogue: null,
    almanacEntries: null,
    tugIntroPlayed: false,
    buddeIntroduced: false,
    scenario3CapacityBriefed: false,
    scenario3Completed: false,
    scenario3TowRequestPlayed: false,
    scenario3TowRequestDeferred: false,
    lastLatencyReminderTick: -Infinity,
    consoleReadyAtMs: now(),
    respondingToCommand: false,
    inbox: [],
    unreadInboxCount: 0,
    inboxOpenIndexes: [],
    news: [],
    factionHeatEnabled: false,
    factionHeat: { ufp: 0, arcworks: 0, blister: 0 },
    activeFactionCampaigns: [],
    nextFactionCampaignRollTick: 0,
    operatingExpenseAccrued: 0,
    operatingExpenseWindowStartTick: 0,
    trafficLocks: {},
    dockConditions: {},
    dockMaintenance: {},
  };
}
